### ISSUE TITLE
Symfony 3.4/4.0 - Attribute "autowire" on service cannot be inherited from "_defaults" when a "parent" is set.

### ISSUE THREAD

**Issue by kironet** [craue/CraueFormFlowBundle#308]
> The "App\Form\Checkout\CheckoutFlow" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

or 

> Attribute "autowire" on service "App\Form\Checkout\CheckoutFlow" cannot be inherited from "_defaults" when a "parent" is set. Move your child definitions to a separate file or define this attribute explicitly in /Users/name/Documents/Projects/Symfony/project-name/config/services.yaml (which is loaded in resource "/Users/name/Documents/Projects/Symfony/project-name/config/services.yaml").

```
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

     App\Form\Checkout\CheckoutFlow:
         public: true
         parent: craue.form.flow
```
