### ISSUE TITLE
Call to a member function getCurrentRequest() on null

### ISSUE THREAD

**Issue by igorjacon** [craue/CraueFormFlowBundle#325]
I know this is a duplicate of issue [318](https://github.com/craue/CraueFormFlowBundle/issues/318) but I'm having the same problem and that issue is closed but no explanation given.

I have the same setup, can someone help?

Thanks

**Comment by igorjacon** [comment]
@craue

**Comment by Andrufus** [comment]
Hi
I solved this by configuring the service like this :
```yml
app.form.registration:
    class: AppBundle\Form\RegistrationFlow
    parent: craue.form.flow
    public: true
    autowire: true
    autoconfigure: false
```

**Comment by Gerfaut** [comment]
Hello @igorjacon, @Andrufus is this quick fix still working with last version of symfony? 
I'm still struggling with the exact same error you had. 

Thanks for your help! 

@craue will this bundle be updated to work with last version of symfony (and the new DI system)? 
Thanks, 

_Gerfaut_

**Comment by Andrufus** [comment]
Hi @Gerfaut 
I used this config with Symfony 3.4.3. I didn't test on any other version.

**Comment by igorjacon** [comment]
Hi @Gerfaut 

It's working for me on Symfony 4.
I created a new service config like so:
```
services:
    App\Form\Vendor\RegistrationFlow\VendorRegistrationType:
        parent: craue.form.flow
        public: true
        autowire: true
        autoconfigure: false
```

**Comment by Gerfaut** [comment]
@igorjacon that's weird, I tried this too on Symfony 4.1.5 and it was not working properly. 
I'll retry this evening :)

**Comment by igorjacon** [comment]
On what service file did you add that service config?
I had to create a different service file.
Hope that helps.

**Comment by igorjacon** [comment]
Awesome, I'm glad it works 👍

**Comment by gnutix** [comment]
I faced the following issue when trying to use the `parent: craue.form.flow` to define my flow service : 

> The service "\Our\Flow" cannot use the "parent" option in the same file where "_instanceof" configuration is defined as using both is not supported. Move your child definitions to a separate file.

We tried moving the service definition to another file, but it didn't work out at first (probably because we forgot clearing the cache at the time). So we used this solution instead :

```
services:
    // our defaults config
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        // others custom definitions here

        Craue\FormFlowBundle\Form\FormFlow:
            calls:
                - [setDataManager, ['@craue.form.flow.data_manager']]
                - [setFormFactory, ['@form.factory']]
                - [setRequestStack, ['@request_stack']]
                - [setEventDispatcher, ['@?event_dispatcher']]
```

It would be nice if this was correctly set by the bundle using Symfony's autoconfigure/_instanceof features.
