### ISSUE TITLE
Symfony 4.1

### ISSUE THREAD

**Issue by igorjacon** [craue/CraueFormFlowBundle#326]
Is this bundle compatible with Symfony4.1?
I'm having an issue using this bundle with a project on Symfony4.1.
Here is my service declaration:

```
services:
    App\Form\ProjectManager\FormFlow\CreateProjectFlowType:
        parent: craue.form.flow
        public: true
        autowire: true
        autoconfigure: false
```
My form extends FormFlow, but when I call the bind method on my form flow
`$flow->bind($project);`
I get the following error:

> Call to a member function getCurrentRequest() on null

Can someone help?
Thanks
